# Generated by Django 4.2.7 on 2024-01-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('cname', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('date_of_joined', models.DateField()),
            ],
        ),
    ]
